[profile.default]
  bytecode_hash = "none"
  src = 'contracts'
  out = 'out'
  libs = ["node_modules", "lib"]
  test = 'test'
  cache_path  = 'cache_forge'
  solc_version = "0.8.25"
  optimizer = true
  optimizer_runs = 1_000_000
  evm_version = 'paris'
